### PR TITLE
Make layer compatible to scarthgap (Yocto Project 5.0)

### PR DESCRIPTION
**Pull request by joergho**
Make the layer compatible to scarthgap by adopting:

- machine configuration
- adapt U-Boot patches (a patch was obsolete because it is already upstream)
- adapt linux-yocto patches (a patch was obsolete because it is already upstream, modify the other patches to make them apply).

Also added config build using [kas](https://kas.readthedocs.io/en/latest/).

### CODE REVIEW

**Comment by joergho** [comment]
**Regarding branching:**

- You'd have to create a branch `mickledore` from the current state
- Apply the PR to master

**What was not yet working:**

The kernel config is not yet completely right, linux-yocto is giving a warning:

```
WARNING: linux-yocto-6.6.17+git-r0 do_kernel_configcheck: [kernel config]: This BSP contains fragments with warnings:

[INFO]: the following symbols were not found in the active configuration:
     - CONFIG_NF_LOG_NETDEV
     - CONFIG_NFT_COUNTER
     - CONFIG_NFT_OBJREF
     - CONFIG_NF_FLOW_TABLE_IPV4
     - CONFIG_IP_NF_TARGET_CLUSTERIP
     - CONFIG_NF_FLOW_TABLE_IPV6
     - CONFIG_NF_LOG_BRIDGE
     - CONFIG_USB_MUSB_AM35X
```

Also, a USB network dongle which is working for `kirkstone` brings the follwing errors:

```
[   15.455815] usb 2-1: New USB device found, idVendor=9710, idProduct=7830, bcdDevice= 1.00
[   15.464658] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   15.472350] usb 2-1: Product: USB-MAC Controller
[   15.477528] usb 2-1: Manufacturer: Moschip Semiconductor
[   15.483238] usb 2-1: SerialNumber: (...)
[   15.498529] PM: Cannot get wkup_m3_ipc handle
```

**Comment by twoerner** [comment]
Thanks for your patches!

As far as I can tell, I was the last (only?) person maintaining this layer. I forked and moved it to https://layers.openembedded.org/layerindex/branch/master/layer/meta-pocketbeagle/ a while ago and maintain it at that location. Does this newer layer work for you?

**Comment by joergho** [comment]
Hi!

I justed tried your `nanbield` branch. Unfortunately `u-boot` has an error in the `initcall sequence`:

```
U-Boot SPL 2023.10 (Oct 02 2023 - 14:39:59 +0000)
Trying to boot from MMC1


U-Boot 2023.10 (Oct 02 2023 - 14:39:59 +0000)

CPU  : AM335X-GP rev 2.1
Model: TI AM335x PocketBeagle
DRAM:  512 MiB
Core:  154 devices, 16 uclasses, devicetree: separate
WDT:   Started wdt@44e35000 with servicing every 1000ms (60s timeout)
NAND:  0 MiB
MMC:   OMAP SD/MMC: 0
Loading Environment from FAT... *** Warning - bad CRC, using default environment

initcall sequence 9ffdb9f8 failed at call 808024d9 (err=-19)
### ERROR ### Please RESET the board ###
```

**Comment by joergho** [comment]
If I change the layer compatibility to `scarthgap` on your `twoerner/master` branch,

- the build succeeds without issues
- the device is able to boot into Linux without issues
- However, I also see the same error with the USB network dongle as mentioned in my first comment.

-> I'm closing the PR. The Your `twoerner/master` branch is already compatible to `scarthgap` , you just have to add it as compatible to the layer info.

**Pull request closed without merging**
